demo_DIR:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_left_joint
        #pid: {p: 0.000001, i: 0.0, d: 0.0}


    back_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_back_joint
        #pid: {p: 0.000001, i: 0.0, d: 0.0}

    right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_right_joint
        #pid: {p: 0.000001, i: 0.0, d: 0.0}

    # Position Controller ------------
    joint_1:
        type: effort_controllers/JointPositionController
        joint: joint_1
        pid: {p: 10.0, i: 5.0, d: 2.0}

    joint_2:
        type: effort_controllers/JointPositionController
        joint: joint_2
        pid: {p: 2.0, i: 5.0, d: 4.0}

    joint_3:
        type: effort_controllers/JointPositionController
        joint: joint_3
        pid: {p: 10.0, i: 5.0, d: 2.0}

    joint_4:
        type: effort_controllers/JointPositionController
        joint: joint_4
        pid: {p: 10.0, i: 5.0, d: 2.0}

    joint_5:
        type: effort_controllers/JointPositionController
        joint: joint_5
        pid: {p: 10.0, i: 5.0, d: 2.0}

    gripper_prismatic_joint_1:
        type: effort_controllers/JointPositionController
        joint: gripper_prismatic_joint_1
        pid: {p: 10.0, i: 5.0, d: 2.0}

    gripper_prismatic_joint_2:
        type: effort_controllers/JointPositionController
        joint: gripper_prismatic_joint_2
        pid: {p: 10.0, i: 5.0, d: 2.0}

    gazebo_ros_control/pid_gains:
        rim_left_joint: {p: 0.01, i: 0.0, d: 0.0}
        rim_back_joint: {p: 0.01, i: 0.0, d: 0.0}
        rim_right_joint: {p: 0.01, i: 0.0, d: 0.0}
