demo_DIR:    
    # Trajectory Controllers ---------------------------------------
    joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - gripper_prismatic_joint_1
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.5
      joint_s:
        trajectory: 0.1
        goal: 0.5
      joint_1:
        trajectory: 0.1
        goal: 0.5
      joint_2:
        trajectory: 0.1
        goal: 0.5
      joint_3:
        trajectory: 0.1
        goal: 0.5
      joint_4:
        trajectory: 0.1
        goal: 0.5
      joint_5:
        trajectory: 0.1
        goal: 0.5
      joint_gripper_prismatic_joint_1:
        trajectory: 0.1
        goal: 0.5
    gains:
      joint_1: {p: 10, d: 0, i: 1, i_clamp: 1}
      joint_2: {p: 10, d: 0, i: 1, i_clamp: 1}
      joint_3: {p: 10, d: 0, i: 1, i_clamp: 1}
      joint_4: {p: 10, d: 0, i: 1, i_clamp: 1}
      joint_5: {p: 10, d: 0, i: 1, i_clamp: 1}
      gripper_prismatic_joint_1: {p: 10, d: 0, i: 1, i_clamp: 1}
