demo_DIR:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_left_joint
        #pid: {p: 0.000001, i: 0.0, d: 0.0}


    back_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_back_joint
        #pid: {p: 0.000001, i: 0.0, d: 0.0}

    right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_right_joint
        #pid: {p: 0.000001, i: 0.0, d: 0.0}

    # Trajectory Controllers ---------------------------------------
    joint_trajectory_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
        constraints:
            goal_time: 2.0
            stopped_velocity_tolerance: 5.0
            joint_1:
                trajectory: 5.1
                goal: 4.5
            joint_2:
                trajectory: 5.1
                goal: 4.5
            joint_3:
                trajectory: 5.1
                goal: 4.5
            joint_4:
                trajectory: 5.1
                goal: 4.5
            joint_5:
                trajectory: 5.1
                goal: 4.5           
        gains:
            joint_1: {p: 100, d: 0, i: 1, i_clamp: 1}
            joint_2: {p: 100, d: 0, i: 1, i_clamp: 1}
            joint_3: {p: 100, d: 0, i: 1, i_clamp: 1}
            joint_4: {p: 100, d: 0, i: 1, i_clamp: 1}
            joint_5: {p: 100, d: 0, i: 1, i_clamp: 1}
        
        state_publish_rate: 25

    hand_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - gripper_prismatic_joint_1
            - gripper_prismatic_joint_2
        constraints:
            goal_time: 2.0
            stopped_velocity_tolerance: 5.0
            gripper_prismatic_joint_1:
                trajectory: 5.1
                goal: 4.5
            gripper_prismatic_joint_2:
                trajectory: 5.1
                goal: 4.5

        gains:
            gripper_prismatic_joint_1: {p: 100, d: 0, i: 10, i_clamp: 1}
            gripper_prismatic_joint_2: {p: 100, d: 0, i: 10, i_clamp: 1}

        state_publish_rate: 25

    gazebo_ros_control/pid_gains:
        rim_left_joint: {p: 0.0001, i: 0.0, d: 0.0}
        rim_back_joint: {p: 0.0001, i: 0.0, d: 0.0}
        rim_right_joint: {p: 0.0001, i: 0.0, d: 0.0}
        joint_1: {p: 100, i: 1, d: 0.0}
        joint_2: {p: 100, i: 1, d: 0.0}
        joint_3: {p: 100, i: 1, d: 0.0}
        joint_4: {p: 100, i: 1, d: 0.0}
        joint_5: {p: 100, i: 1, d: 0.0}
        gripper_revolute_joint: {p: 100, i: 1, d: 0.0}
        gripper_prismatic_joint_1: {p: 100, i: 1, d: 0}
        gripper_prismatic_joint_2: {p: 100, i: 1, d: 0}

