controller_list:
  - name: fake_widowx_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - gripper_prismatic_joint_1
initial:  # Define initial robot poses.
  - group: widowx
    pose: watch