obstacle_range: 1.5 #1.5
raytrace_range: 2.5 #2.0
#footprint: [[0.05,0.3], [0.05,-0.3], [-0.44,-0.05], [-0.45,0.05]]
robot_radius: 0.001
map_topic: map
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_footprint
transform_tolerance: 0.2
always_send_full_costmap: true
plugins: 
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
inflation:
    inflation_radius:  0.5
    cost_scaling_factor: 2.0
cost_factor: 0.55
neutral_cost: 66
lethal_cost: 253
