obstacle_range: 6.0
raytrace_range: 8.5
#footprint: [[0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4]]
robot radius: 0.5
map_topic: map
subscribe_to_updates: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_multi, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_footprint
always_send_full_costmap: true
footprint_padding: 0.02
transform_tolerance: 1.0
update_frequency: 4
publish_frequency: 0.5