obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4]]
robot_radius: 0.25
map_topic: map
subscribe_to_updates: true
observation_sources: scan
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan_multi, marking: true, clearing: true,inf_is_valid: true}
global_frame: map
robot_base_frame: base_footprint
always_send_full_costmap: true
footprint_padding: 0.01
update_frequency: 4.0
publish_frequency: 3.0
controller_frequency: 2.5
