global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 15
  height: 15
  rolling_window: true
  inflation_radius: 0.1
  resolution: 0.1
  plugins: 
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
