local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5
  publish_frequency: 5
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.1
  plugins: 
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
  inflation:
    inflation_radius: 0.8
    cost_scaling_factor: 4 # larger number = lower cost elevation
