local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 4.0
  rolling_window: false
  track_unknown_space: true
  width: 3
  height: 3
  resolution: 0.05
  plugins: 
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
  inflation:
    inflation_radius: 0.1
    cost_scaling_factor: 2.0 # larger number = lower cost elevation
  static_layer:
    static_map: false 
