TrajectoryPlannerROS:
 max_vel_x: 1.0
 min_vel_x: 0.3
 max_vel_theta: 2.0
 min_vel_theta: 0.8
 min_in_place_vel_theta: 0.5
 acc_lim_theta: 1.0
 acc_lim_x: 1.5
 acc_lim_Y: 1.5
 holonomic_robot: true
 meter_scoring: true 
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.1
 occdist_scale:  0.01
 path_distance_bias: 0.4
 goal_distance_bias: 0.2
 controller_frequency: 2
 transform_tolerance: 0.3
